config/routes.rb
Rails.application.routes.draw do
  resources :trust_me_nots

end

app/models/trust_me_not.rb
class TrustMeNot < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trust_me_nots_controller.rb
class TrustMeNotsController < ApplicationController
  before_action :set_trust_me_not, only: [:show, :edit, :update, :destroy]

  # GET /trust_me_nots
  # GET /trust_me_nots.json
  def index
    @trust_me_nots = TrustMeNot.all
  end

  # GET /trust_me_nots/1
  # GET /trust_me_nots/1.json
  def show
  end

  # GET /trust_me_nots/new
  def new
    @trust_me_not = TrustMeNot.new
  end

  # GET /trust_me_nots/1/edit
  def edit
  end

  # POST /trust_me_nots
  # POST /trust_me_nots.json
  def create
    @trust_me_not = TrustMeNot.new(trust_me_not_params)

    respond_to do |format|
      if @trust_me_not.save
        format.html { redirect_to @trust_me_not, notice: 'Trust me not was successfully created.' }
        format.json { render :show, status: :created, location: @trust_me_not }
      else
        format.html { render :new }
        format.json { render json: @trust_me_not.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trust_me_nots/1
  # PATCH/PUT /trust_me_nots/1.json
  def update
    respond_to do |format|
      if @trust_me_not.update(trust_me_not_params)
        format.html { redirect_to @trust_me_not, notice: 'Trust me not was successfully updated.' }
        format.json { render :show, status: :ok, location: @trust_me_not }
      else
        format.html { render :edit }
        format.json { render json: @trust_me_not.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trust_me_nots/1
  # DELETE /trust_me_nots/1.json
  def destroy
    @trust_me_not.destroy
    respond_to do |format|
      format.html { redirect_to trust_me_nots_url, notice: 'Trust me not was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trust_me_not
      @trust_me_not = TrustMeNot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trust_me_not_params
      params.require(:trust_me_not).permit(:title, :notes, :due, :done)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trust_me_nots_helper.rb
module TrustMeNotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrustMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trust_me_nots/_form.html.erb
<%= form_for(@trust_me_not) do |f| %>
  <% if @trust_me_not.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trust_me_not.errors.count, "error") %> prohibited this trust_me_not from being saved:</h2>

      <ul>
      <% @trust_me_not.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.date_select :due %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trust_me_nots/edit.html.erb
<h1>Editing trust_me_not</h1>

<%= render 'form' %>

<%= link_to 'Show', @trust_me_not %> |
<%= link_to 'Back', trust_me_nots_path %>

app/views/trust_me_nots/index.html.erb
<h1>Listing trust_me_nots</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Notes</th>
      <th>Due</th>
      <th>Done</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trust_me_nots.each do |trust_me_not| %>
      <tr>
        <td><%= trust_me_not.title %></td>
        <td><%= trust_me_not.notes %></td>
        <td><%= trust_me_not.due %></td>
        <td><%= trust_me_not.done %></td>
        <td><%= link_to 'Show', trust_me_not %></td>
        <td><%= link_to 'Edit', edit_trust_me_not_path(trust_me_not) %></td>
        <td><%= link_to 'Destroy', trust_me_not, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trust me not', new_trust_me_not_path %>

app/views/trust_me_nots/new.html.erb
<h1>New trust_me_not</h1>

<%= render 'form' %>

<%= link_to 'Back', trust_me_nots_path %>

app/views/trust_me_nots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @trust_me_not.title %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @trust_me_not.notes %>
</p>

<p>
  <strong>Due:</strong>
  <%= @trust_me_not.due %>
</p>

<p>
  <strong>Done:</strong>
  <%= @trust_me_not.done %>
</p>

<%= link_to 'Edit', edit_trust_me_not_path(@trust_me_not) %> |
<%= link_to 'Back', trust_me_nots_path %>